### ISSUE TITLE
Doesn't seem to do what it says on the tin

### ISSUE THREAD

**Issue by gotofritz** [geejs/gulp-tap#10]
Hi. Not clear how I am supposed to use gulp-tap as documentation is so terse. 

I have a task which generates a main.js and an external sourcemap for it. I want just the js file to be gzipped.

First without gulp-tap - everything ok

    gulp task("x", function() {
      return gulp
      .src("some/files")
      // do some webpack stuff
      .pipe(webpackStream({}))
      // create an external sourcemap
      .pipe(sourcemaps.init({loadMaps: true}))
      .pipe(sourcemaps.write("./"))
      // here I have two files -  a main.js and a main.js.map
      // both are gzipped
      .pipe(gzip())
      // here I get main.js, main.js.map, main.js.gz and main.js.map.gz
      .pipe(gulp.dest("some/where"));
    }

The pipe(tap part runs (I get log messages at the appropriate place) but  doesn't do anything /

    gulp task("x", function() {
      return gulp
      .src("some/files")
      // do some webpack stuff
      .pipe(webpackStream({}))
      // create an external sourcemap
      .pipe(sourcemaps.init({loadMaps: true}))
      .pipe(sourcemaps.write("./"))
      // here I have two files -  a main.js and a main.js.map
      // I only want to gzip the main.js
      .pipe(tap(function(file, t) {
          if (path.extname(file.path) === ".js") {
            // so far it works - i see the message
            console.log("MATCHED: ", file.path);
            return t.through(gzip, [{ gzipOptions: { level: 9 } }]);
          }
      }))
      // but here I get only main.js. No  main.js.gz, main.js.map nor main.js.map.gz
      .pipe(gulp.dest("some/where"));
    }

Thanks.

**Comment by gotofritz** [comment]
Oh - another dead project

**Comment by revelt** [comment]
I have huge suspicion that `file.path` won't work because `file` is actually a Buffer-type!
