### ISSUE TITLE
builds 'incomplete' stream objects

### ISSUE THREAD

**Issue by tcurdt** [geejs/gulp-tap#11]
The stream objects `gulp-tap` outputs seem to be incomplete and using `stream.Readable.wrap` on them fails.

**Comment by joepie91** [comment]
Clarification:

The following happens.

```
[17:42:44] TypeError: undefined is not a function
    at Readable.wrap (_stream_readable.js:763:10)
    at makeStreams2 (/Users/xxx/Downloads/blog/node_modules/combined-stream2/lib/combined-stream2.js:39:35)
    ...
```

This points at [this line](https://github.com/joyent/node/blob/v0.12.4/lib/_stream_readable.js#L763), indicating there's no `.on` method. The following output is printed when `console.log`ing the object:

```
{ domain: null,
  _events: 
   { end: [Function],
     drain: [Function: ondrain],
     error: [Function: onerror],
     close: [Function: cleanup] },
  _maxListeners: undefined,
  writable: true,
  readable: true,
  paused: false,
  autoDestroy: true,
  write: [Function],
  push: [Function],
  queue: [Function],
  end: [Function],
  destroy: [Function],
  pause: [Function],
  resume: [Function] }
```

**Comment by dotnetCarpenter** [comment]
Please test again with the [latest release](https://github.com/geejs/gulp-tap/releases).

**Comment by dotnetCarpenter** [comment]
@tcurdt and @joepie91 do you have a link to your old code that broke? If yes, can you post it here, so I can create a test-case?

I'm closing this for now, until I get further information.
