### ISSUE TITLE
How is the `t.through` function different from `gulp-if`?

### ISSUE THREAD

**Issue by robwierzbowski** [geejs/gulp-tap#12]
gulp-if's filters streams by any number of conditions. Does the  `t.through` function do anything significantly different, and if not should it be removed to comply with gulp's "do one thing and do it well" policy?

**Comment by dotnetCarpenter** [comment]
*gulp-tap* doesn't imply any filtering at all. It's a short cut for writing a gulp plugin, you just pass in an anonymous function instead of creating an entire gulp plugin.

Please correct me, if I'm wrong. I don't know *gulp-if* at all.
