### ISSUE TITLE
Does absolutely nothing

### ISSUE THREAD

**Issue by lpender** [geejs/gulp-tap#14]
Input:

```
  return gulp.src('src/*.js')
    .pipe(debug())
    .pipe(tap(function (file) {
      gutil.log('here')
      console.log('here')
  ...
```

Output:

```
[12:50:58] gulp-debug: src/turf-player.js
[12:50:58] gulp-debug: src/turf-slider.js
[12:50:58] gulp-debug: 2 items
[12:50:58] Finished 'js' after 72 ms
```

**Comment by revelt** [comment]
I believe you need to tap the deeper keys of the `file`, for example, `file.contents` returns a buffer, which you need to convert to a string first:
https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end

This library does work, it's just not well documented. I just created a Wiki and uploaded the first code example.

**Comment by revelt** [comment]
For posterity, see [Wiki](https://github.com/geejs/gulp-tap/wiki) for use examples.
