### ISSUE TITLE
How to feed taps back into the stream

### ISSUE THREAD

**Issue by cferdinandi** [geejs/gulp-tap#2]
Forgive me for opening an issue for what is more of a "how to" question, but I've Googled, dug through the documentation and source code, and looked around on StackOverflow without much luck...

I want to be able to be able to compile individual files in my `js` folder as normal, but concatenate content placed in subdirectories and assign the folder name to the concatenated file. `gulp-tap` makes it easy to check if the current item is a directory vs. a file, but I can't figure out how to funnel my work back into the stream...

**Example Source**

```
|-- js/
|   |-- main/
|   |   |-- script1.js
|   |   |-- script2.js
|   |   |-- script3.js
|   |-- detects/
|   |   |-- scriptA.js
|   |   |-- scriptB.js
|   |   |-- scriptC.js
|   |-- myplugin.js
|   |-- myplugin2.js
```

**Example Output**

```
|-- js/
|   |-- myplugin.js
|   |-- myplugin.min.js
|   |-- myplugin2.js
|   |-- myplugin2.min.js
|   |-- main.js
|   |-- main.min.js
|   |-- detects.js
|   |-- detects.min.js
```

**What I've tried**

```js
gulp.task('scripts', ['clean'], function() {
    return gulp.src('src/js/*')
        .pipe(plumber())
        .pipe(flatten())
        .pipe(tap(function (file, t) {
            if ( file.stat.isDirectory() ) {
                var name = file.relative + '.js';
                return gulp.src(file.path + '/*.js')
                    .pipe(concat(name))
                    .pipe(gulp.dest(paths.scripts.output));
            }
        }))
        .pipe(gulp.dest(paths.scripts.output));
});
```

This actually works, but I don't like that I'm repeating code both in and after `gulp-tap`. Ideally I should be able to do something like this and have it feed back into the stream:

```js
gulp.task('scripts', ['clean'], function() {
    return gulp.src('src/js/*')
        .pipe(plumber())
        .pipe(flatten())
        .pipe(tap(function (file, t) {
            if ( file.stat.isDirectory() ) {
                var name = file.relative + '.js';
                return gulp.src(file.path + '/*.js')
                    .pipe(concat(name));
            }
        }))
        .pipe(header(banner.full, { package : package }))
        .pipe(gulp.dest(paths.scripts.output))
        .pipe(rename({ suffix: '.min.' + Date.now() }))
        .pipe(uglify())
        .pipe(header(banner.min, { package : package }))
        .pipe(gulp.dest(paths.scripts.output));
});
```

However, the subdirectory files are never compiled to the `dest` this way. other things I've tried that have not worked either:

**1**

```js
.pipe(tap(function (file, t) {
    if ( file.stat.isDirectory() ) {
        var name = file.relative + '.js';
        t.through(gulp.src(file.path + '/*.js')
            .pipe(concat(name)));
    }
}))
```

**2**

```js
.pipe(tap(function (file, t) {
    if ( file.stat.isDirectory() ) {
        var name = file.relative + '.js';
        .pipe(gulp.src(file.path + '/*.js')
            .pipe(concat(name)));
    }
}))
```

**3**

```js
.pipe(tap(function (file, t) {
    if ( file.stat.isDirectory() ) {
        var name = file.relative + '.js';
        gulp.src(file.path + '/*.js')
            .pipe(concat(name));
    }
}))
```

**4**

```js
.pipe(tap(function (file, t) {
    var scripts;
    if ( file.stat.isDirectory() ) {
        var name = file.relative + '.js';
        scripts = gulp.src(file.path + '/*.js')
            .pipe(concat(name));
    }
    return scripts;
}))
```

I've got functioning code so I'm not totally stuck, but I know there's a better way to do this. I would also like to be checking for a `.js` extension before compiling to `dist` (something covered for styles already because I'm only grabbing `.scss` files). Any insights here would be greatly appreciated.

**Comment by waynedpj** [comment]
> @waynedpj - I should note there are some dependencies and path variables in that task that aren't reflected in snippet I shared. View the source link for the full code.

@cferdinandi thanks for clarifying and sorry for my delayed response. i was originally doing a similar thing with [stream-combiner2](https://github.com/substack/stream-combiner2).  however, i eventually hacked something together that works as i had originally hoped.  hopefully i can get it cleaned up and released sometime.

thanks again.

**Comment by cferdinandi** [comment]
@waynedpj Is what I'm trying to do outside of the scope of gulp-tap? If so, I'm happy to close this issue. I've got something working using Lazypipe, and that may be the preferred approach based on how gulp-tap is designed to work.

**Comment by waynedpj** [comment]
@impinball thanks so much for the packages and clues. part of the reason for my delayed reply was trying to figure out if these packages would fit the bill.  w/o bombarding this already digressed issue w/ more digression, unfortunately i could find out how to make them work as i requested.  gulp-foreach and through-pipes both seemed like the answer to my prayers, but either through my lack of stream/JS understanding or them not providing the needed functionality, i could not solve my problem with either.  neither actually pauses the main stream, which for my setup is critical.  anyway, as mentioned above i put together a little package that will work similar to gulp-foreach, but buffers/pauses the main stream/pipeline until the sub stream created by the foreach finishes.  hopefully i will learn enough JS/npm/etc. to get it cleaned up and shared.  anyway, apologies for my delayed response and thanks again.

**Comment by waynedpj** [comment]
> @waynedpj Is what I'm trying to do outside of the scope of gulp-tap? If so, I'm happy to close this issue. I've got something working using Lazypipe, and that may be the preferred approach based on how gulp-tap is designed to work.

@cferdinandi according to my very novice understanding of streams, i think so.  if i understand correctly (big IF), gulp-tap just mainly provides a way to execute code for each vinyl that comes down the pipeline/stream.
to solve my problem, i basically had to create a stream filter (via [through2](https://github.com/rvagg/through2)) in the main stream/pipeline that would create+execute a new sub stream for each vinyl received, not forwarding that original vinyl on down the main pipeline/stream until the associated sub stream had ended.  i thought maybe gulp-tap could do this, and maybe someone w/ a better understanding could make it work, but in my research it really did not help for reusing sub streams the way i (and perhaps you?) were thinking.  of course, gulp-tap is obviously very useful in many other cases.
hope that helps.

**Comment by impinball** [comment]
@waynedpj Also, check out [gulp-if](https://www.npm.com/packages/gulp-if). It may not help in this particular use case, but it's helpful for other things. Keep in mind that it and gulp-filter aren't exactly the most compatible. It would definitely be useful with through-pipes or lazypipe being used to keep it dry.

**Comment by waynedpj** [comment]
@impinball i had checked out gulp-if, but was not aware of the compatibility issue with gulp-filter.  thanks for the heads up and again for all the help.

**Comment by impinball** [comment]
@waynedpj Actually, I meant lazypipe and gulp-if/gulp-filter. My bad.

**Comment by v8xm** [comment]
Mark! 
Thank you !

**Comment by elliottregan** [comment]
I has a similar issue, and I solved it using `gulp-foreach` instead of `gulp-tap`. 

https://stackoverflow.com/questions/44510725/how-do-you-pass-a-filename-to-the-next-action-in-a-gulp-pipeline-using-gulp-tap/44510726#44510726
