### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by sigfriedCub1990** [geejs/gulp-tap#23]
Hello @dotnetCarpenter, are maintaining this repository? I think I can help with this taks if you don't have time.

**Comment by dotnetCarpenter** [comment]
@sigfriedCub1990 That would be most welcome! Especially as I'm not an active user of gulp-tap anymore.

Looking at travis test of #24 and it seems our travis environment is out of sync with what gulp-tap is suppose to run on (node >= 8 and not node 4-6). I will update `.travis` and re-run your PR.

**Comment by dotnetCarpenter** [comment]
@sigfriedCub1990 You are invited
