### ISSUE TITLE
change file.base twice will end with "Error: no writecb in Transform classh"

### ISSUE THREAD

**Issue by nxf** [geejs/gulp-tap#5]
For some reason, I need change 'base' property of current file, after that I will change back old 'base' property. The code looks like this: 
```js
.pipe(tap(function(file){
   file.old_base = file.base;  
   file.base = file.base+"js/";  
}))
.pipe(something_otherprocessing())
.pipe(tap(function(file){
  file.base = file.old_base;
}))
```

When running, It will throw exception *"Error: no writecb in Transform classh"*.  when I remove the second tap calling, running will be ok, but I can not get the original 'base' property.

So any one can help me out?

**Comment by dotnetCarpenter** [comment]
@nxf What is the `something_otherprocessing()` doing? I tried to reproduce your exception in edea6ee [tests/dest.test.coffee#L86](https://github.com/geejs/gulp-tap/blob/edea6ee29ec583d07d52b1e7ae0067f67af4699a/tests/dest.test.coffee#L86) but to no avail.

**Comment by dotnetCarpenter** [comment]
Please test again with the [latest release](https://github.com/geejs/gulp-tap/releases).

**Comment by dotnetCarpenter** [comment]
@nxf  do you have a link to your old code that broke? If yes, can you post it here, so I can create a test-case?

I'm closing this for now, until I get further information.
