### ISSUE TITLE
Using gulp.dest with changing path fails because of caching in gulp.tap

### ISSUE THREAD

**Issue by dotnetCarpenter** [geejs/gulp-tap#6]
I'm still investigating and will update this issue with my findings.
But the crux of the problem is that:

``` javascript
return t.through(gulp.dest, [destPath]);
```

will cache `gulp.dest` which is a wrapper for [vinyl-fs](https://github.com/wearefractal/vinyl-fs/) which uses a closure to set `outFolder` and when gulp-tap caches `gulp.dest` the `outFolder` never change.

An idea that comes to mind is to implement caching as a typical **memoize function** - which includes arguments.

**Comment by Fiery** [comment]
Thanks for the information. I just encountered the same problem as well when trying to pass stream through multiple gulp.dest()s. The quick dirty patch on this might only be manually changing gulp.dest's __tapId and I know that is not good 'cause __tapId ought to be designed as private member of the filter argument, at least it looks so. I've tried to delete the returned stream from t.through() every time I wanted to have new stream instance, it didn't work though, probably I've only deleted a copy of the stream. I am wondering why is caching introduced and I am not sure removing caching would be the best solution. I do need to increase the emitter._maxListeners to get rid of the warnings though as I fixed it in my way.

**Comment by dotnetCarpenter** [comment]
@Fiery I know this is old but I only just saw your comment.

There is no good reason to have this cache, it doesn't speed up execution because it is just a reference to a function which is cached. Something the JS engine will do anyway. If you where using a closure, you might want to cache the function but this make no sense to do in general as `gulp-tap` has no idea about the nature of the function it caches. It's one of those things that might appear as a good idea at first but it's horrible in reality. 

This has been fixed in #7 and implemented in both @Javey and my fork of this project.

@Javey: https://github.com/Javey/gulp-tap
@dotnetCarpenter: https://github.com/dotnetCarpenter/gulp-tap

**Comment by mgutz** [comment]
@dotnetCarpenter I added you as admin collaborator. What is your userName on npm? I'll add you as an owner. I rarely use gulp anymore in favor of webpack.

**Comment by dotnetCarpenter** [comment]
@mgutz thanks! Could you add @Javey as well? I really really don't have time but `gulp-tap` is useful project and being admin gives me some freedom to fix issues. It just don't give me any time.

To everyone else; bugs will be fixed but slowly - do a really good PR, with unit tests and you help the world for the better! :dancing_men:

**Comment by dotnetCarpenter** [comment]
fixed

**Comment by dotnetCarpenter** [comment]
@mgutz Seems that you have not added me on npm - I'm not allowed to publish *gulp-tap*. My user name is the same as on github: [dotnetcarpenter](https://www.npmjs.com/~dotnetcarpenter)

**Comment by mgutz** [comment]
@dotnetCarpenter done

**Comment by dotnetCarpenter** [comment]
damn. it's publishing under my account and not under geejs/gulp-tap. I'll need to contact npm...
