### ISSUE TITLE
Parent stream ends before all child substreams

### ISSUE THREAD

**Issue by jedmao** [geejs/gulp-tap#9]
See https://github.com/twolfson/gulp.spritesmith/issues/55 for the original issue.

**Comment by dotnetCarpenter** [comment]
Please test again with the [latest release](https://github.com/geejs/gulp-tap/releases).

**Comment by dotnetCarpenter** [comment]
@jedmao Do you have a link to your old code that didn't work with gulp-tap? If so can you post it here, so I can create a test case?

I'm closing this for now, until I get further information.

**Comment by jedmao** [comment]
The issue was with [gulp-tap](https://github.com/twolfson/gulp.spritesmith/issues/55#issuecomment-122437634), so you're right to close this.

**Comment by dotnetCarpenter** [comment]
@jedmao This is gulp-tap 😅
But I've changed some things since July 2015 and was wondering if I could use your issue as a test case. It's probably fixed now, but I'm not 100% sure.

**Comment by jedmao** [comment]
LOL whoops! Not sure if it's fixed but I've moved away from gulp-tap to through so I've dodged it for now.

**Comment by dotnetCarpenter** [comment]
Did you ever commit the failing code and have it in a public repository? If yes, then I can create a test case that cover your old issue.

gulp-tap has over a 100 dependents so I would like to make sure that it does not happen again. But I guess no one was using `.through` in gulp-tap, since it was badly broken.

Using through makes sense, gulp-tap uses [through2](https://github.com/rvagg/through2) now.

**Comment by jedmao** [comment]
I never committing the failing code because it was failing, but I did provide the failing code [here](https://github.com/twolfson/gulp.spritesmith/issues/55#issue-95492323).

I tried to reproduce the issue just now, but our gulpfile has evolved a lot since back then and, actually, we're retiring gulp entirely this next week.

**Comment by dotnetCarpenter** [comment]
Moving to webpack?

**Comment by jedmao** [comment]
Yep! We had webpack before, but we were also using gulp for a number of tasks. Not any more!
